let User,CustomErrorHandler;_828‍.x([["default",()=>_828‍.o]]);_828‍.w("../../models",[["User",["User"],function(v){User=v}]]);_828‍.w("../../services/CustomeErrorHandler",[["default",["CustomErrorHandler"],function(v){CustomErrorHandler=v}]]);

const userControllers = {
  async getUser(req, res, next) {
    try {
      const user = await User.findOne({ _id: req.user._id }).select(
        "-password -createdAt -updatedAt -__v"
      );
      if (!user) {
        // console.log("afaa");
        return next(CustomErrorHandler.notFound());
      }
      res.json(user);
    } catch (error) {
      return next(CustomErrorHandler.notFound());
    }
  },
};

_828‍.d(userControllers);
